version: '3'
services:
  watchit_migrator:
    image: gmena/watchit:v1.0.1
    container_name: watchit_migrator
    command: bash -c "export PYTHONPATH=$PYTHONPATH:/data/watchit && python resource/py/migrate.py"
    depends_on:
      - watchit_mongodb

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

