version: '3'
services:
  watchit_ipfs:
    image: gmena/node:v1.1.3
    restart: unless-stopped
    volumes:
      - ./src/ipfs/config:/data/ipfs/config
    ports:
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "5001:5001"

  watchit_test:
    image: gmena/migrate:v1.1.0
    container_name: watchit_test
    command: python3 test.py
    volumes:
      - .:/data/watchit
    env_file:
      - .env

  watchit_migrator:
    image: gmena/migrate:v1.0.23
    container_name: watchit_migrator
    command: python3 migrate.py
    links:
      - "watchit_mongodb:mongodb"
      - "watchit_ipfs:ipfs"
    volumes:
      - .:/data/watchit
    env_file:
      - .env
    depends_on:
      - watchit_mongodb
      - watchit_ipfs
      - watchit_orbitdb_api

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  watchit_worker:
    image: gmena/node:v1.1.2
    restart: unless-stopped
    command: [ 'bash', '-c', 'src/bash/worker.sh' ]
    volumes:
      - .:/data/watchit
    depends_on:
      - watchit_orbitdb_api

  watchit_orbitdb_api:
    image: phillmac/orbit-db-http-api-dev:debug
    restart: unless-stopped
    command: [ "node", "--trace-warnings", "src/cli.js", "api", "--debug" ]
    environment:
      IPFS_HOST: 'watchit_ipfs'
      ORBITDB_DIR: '/orbitdb'
      FORCE_HTTP1: 'true'
      ANNOUNCE_DBS: 'true'
      LOG: 'DEBUG'
    depends_on:
      - watchit_ipfs
    ports:
      - 127.0.0.1:3001:3000/tcp
    volumes:
      - ./orbitdb:/orbitdb
