version: '3'
services:
  watchit_migrator:
    image: gmena/watchit:v1.0.0
    container_name: watchit_migrator
    restart: unless-stopped
    volumes:
      - .:/data/watchit/
    command: tail -f .gitignore
    depends_on:
      - watchit_mongodb

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

