version: '3'
services:
  watchit_migrator:
    container_name: watchit_migrator
    restart: unless-stopped
    volumes:
      - .:/data/watchit/
    #  command: bash -c "export PYTHONPATH=$PYTHONPATH:/data/watchit && python resource/py/migrate.py"
    command: tail -f .gitignore
    build: resource
    ports:
      - "8050:80"
    depends_on:
      - watchit_mongodb

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

