version: '3'
services:
  watchit_ipfs:
    image: gmena/node:v1.1.2
    restart: unless-stopped
    volumes:
    - ~/.ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "5001:5001"

  watchit_migrator:
    image: gmena/migrate:v1.0.23
    container_name: watchit_migrator
    command: python3 migrate.py
    links:
      - "watchit_mongodb:mongodb"
      - "watchit_ipfs:ipfs"
    volumes:
      - .:/data/watchit
    env_file:
      - .env
    depends_on:
      - watchit_mongodb
      - watchit_ipfs

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

  watchit_orbitdb_api:
    image:  phillmac/orbit-db-http-api-dev:debug
    restart: unless-stopped
    command: ["node", "--trace-warnings", "src/cli.js", "api", "--debug"]
    environment:
      IPFS_HOST: 'watchit_ipfs'
      ORBITDB_DIR: '/orbitdb'
      FORCE_HTTP1: 'true'
      ANNOUNCE_DBS: 'true'
      LOG: 'DEBUG'
    depends_on:
      - watchit_ipfs
    ports:
      - 127.0.0.1:3001:3000/tcp
    volumes:
      - ./orbitdb:/orbitdb
