version: '3'
services:
  watchit_migrator:
    image: gmena/watchit:v1.0.2
    container_name: watchit_migrator
    command: python3 resource/py/migrate.py
    env_file:
      - .env
    depends_on:
      - watchit_mongodb

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

