version: '3'
services:
  watchit_ipfs:
    image: gmena/node:v1.0.5
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "5001:5001"

  watchit_migrator:
    image: gmena/migrate:v1.0.17
    container_name: watchit_migrator
    command: python3 src/py/migrate.py
    links:
      - "watchit_mongodb:mongodb"
      - "watchit_ipfs:ipfs"
    volumes:
      - .:/data/watchit
    env_file:
      - .env
    depends_on:
      - watchit_mongodb
      - watchit_ipfs

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

