version: '3'
services:
  watchit_ipfs:
    image: ipfs/go-ipfs:v0.6.0
    restart: unless-stopped
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    volumes:
      - ./resource/bash/init_ipfs.sh:/usr/local/bin/start_ipfs
      #- ~/.ipfs/swarm.key:/data/ipfs/swarm.key
    ports:
      - "4001:4001"
      - "4002:4002"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"

  watchit_migrator:
    image: gmena/watchit:v1.0.2
    container_name: watchit_migrator
    command: python3 resource/py/migrate.py
    env_file:
      - .env
    depends_on:
      - watchit_mongodb
      - watchit_ipfs

  watchit_mongodb:
    image: mongo
    container_name: watchit_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

