version: '3'
services:
  watchit_ipfs:
    image: gmena/node:v1.1.3
    restart: unless-stopped
    ports:
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "5001:5001"

  watchit_worker:
    image: gmena/node:v1.1.2
    restart: unless-stopped
    command: [ 'bash', '-c', 'src/bash/worker.sh' ]
    volumes:
      - .:/data/watchit
    depends_on:
      - watchit_orbitdb_api

  watchit_orbitdb_api:
    image: phillmac/orbit-db-http-api-dev:debug
    restart: unless-stopped
    command: [ "node", "--trace-warnings", "src/cli.js", "api", "--debug" ]
    environment:
      IPFS_HOST: 'watchit_ipfs'
      ORBITDB_DIR: '/orbitdb'
      FORCE_HTTP1: 'true'
      ANNOUNCE_DBS: 'true'
      LOG: 'DEBUG'
    depends_on:
      - watchit_ipfs
    ports:
      - 127.0.0.1:3001:3000/tcp
    volumes:
      - ./orbitdb:/orbitdb
